export const streamConfig = {
  college: [
    {
      title: "Arts",
      icon: "graduation-cap",
      subjects: [
        "English",
        "M.I.L. (Assamese, Bengali, Hindi) / Alternative English",
        "Economics",
        "Political Science",
        "Logic & Philosophy",
        "Education",
        "Mathematics",
        "Advance Assamese / Advance Hindi",
        "Sociology",
        "Geography",
        "Sanskrit",
        "Swadesh Adhyayan",
        "History",
        "Retail Trade",
        "Bihu",
        "Computer Science & Application",
        "Artificial Intelligence",
        "Financial Literacy",
        "Sign Language",
      ],
    },
    {
      title: "Science",
      icon: "atom",
      subjects: [
        "English",
        "M.I.L. (Assamese, Bengali, Hindi) / Alternative English",
        "Physics",
        "Chemistry",
        "Biology",
        "Mathematics",
        "Statistics",
        "Geography & Economics",
        "Computer Science & Application",
        "Artificial Intelligence",
        "Financial Literacy",
        "Sign Language",
      ],
    },
    {
      title: "Commerce",
      icon: "indian-rupee",
      subjects: [
        "English",
        "M.I.L. (Assamese, Bengali, Hindi) / Alternative English",
        "Accountancy",
        "Business Studies",
        "Economics",
        "Business Mathematics and Statistics (BMST)",
        "Finance",
        "Retail Trade",
        "Computer Science & Application",
        "Artificial Intelligence",
        "Financial Literacy",
        "Sign Language",
      ],
    },
  ],
  school: [
    {
      title: "Nursery",
      icon: "graduation-cap",
      subjects: [
        "Conversation",
        "Maths",
        "Cursive",
        "Rhymes",
        "English",
        "Arts & Craft",
      ],
    },
    {
      title: "L.K.G",
      icon: "graduation-cap",
      subjects: [
        "Conversation",
        "Maths",
        "Rhymes",
        "Assamese",
        "Cursive",
        "English",
        "Arts & Craft",
      ],
    },
    {
      title: "U.K.G",
      icon: "graduation-cap",
      subjects: [
        "Conversation",
        "Rhymes",

        "Assamese",
        "Science",
        "Maths",
        "Cursive",

        "English",
        "Art & Craft",
        "Hindi",
      ],
    },
    {
      title: "Class I",
      icon: "graduation-cap",
      subjects: [
        "Moral Science",
        "English I",
        "English II",
        "Conversation",

        "Assamese",
        "Art & Craft",
        "Hindi",
        "Mathematics",
        "Social Science",

        "General Science",
        "G.K.",
      ],
    },
    {
      title: "Class II",
      icon: "graduation-cap",
      subjects: [
        "Moral Science",
        "English I",
        "Conversation",

        "Assamese",
        "Maths",
        "Social Science",
        "General Science",
        "Hindi",
        "G.K.",

        "Computer",
        "English II",
        "Art & Craft",
      ],
    },
    {
      title: "Class III",
      icon: "graduation-cap",
      subjects: [
        "Moral Science",
        "English I",
        "Conversation",

        "Assamese",
        "Maths",
        "Social Science",
        "General Science",
        "Hindi",
        "G.K.",

        "English II",
        "Computer",
        "Art & Craft",
      ],
    },
    {
      title: "Class IV",
      icon: "graduation-cap",
      subjects: [
        "Moral Science",
        "English I",
        "Conversation",

        "Assamese",
        "Maths",
        "Social Science",
        "General Science",
        "Hindi",
        "G.K.",

        "Art & Craft",
        "Computer",
        "English II",
      ],
    },
    {
      title: "Class V",
      icon: "graduation-cap",
      subjects: [
        "Moral Science",
        "English",
        "Conversation",
        "Assamese",

        "Maths",
        "Social Science",
        "General Science",
        "Hindi",
        "G.K.",

        "Computer",
        "Art & Craft",
        "English II",
      ],
    },
    {
      title: "Class VI",
      icon: "graduation-cap",
      subjects: [
        "Maths",
        "Social Science",
        "General Science",
        "Hindi",

        "G.K.",
        "Moral Science",
        "English",
        "Assamese",

        "Spoken English",

        "English II",
        "Computer",
      ],
    },
    {
      title: "Class VII",
      icon: "graduation-cap",
      subjects: [
        "Moral Science",
        "English",
        "Assamese",

        "Spoken English",

        "English II",
        "Computer",
        "Maths",
        "Social",
        "General Science",
        "Hindi",

        "G.K.",
      ],
    },
    {
      title: "Class VIII",
      icon: "graduation-cap",
      subjects: [
        "Maths",
        "Social Science",
        "Science",
        "Hindi",

        "G.K.",
        "English II",
        "Computer",
        "Hindi (E)",
        "English",
        "Assamese",
        "Spoken English",
      ],
    },
    {
      title: "Class IX",
      icon: "graduation-cap",
      subjects: [
        "English",
        "MIL (Assamese/Hindi)",
        "General Science",
        "Social Science",
        "Mathematics",
        "Elective (Hindi/Adv Maths/Adv Geography/Computer/Commerce)",
      ],
    },
    {
      title: "Class X",
      icon: "graduation-cap",
      subjects: [
        "English",
        "MIL (Assamese/Hindi)",
        "General Science",
        "Social Science",
        "Mathematics",
        "Elective (Hindi/Adv Maths/Adv Geography/Computer/Commerce)",
      ],
    },
  ],
};
