CREATE TABLE IF NOT EXISTS staff (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  image_url VARCHAR(500) NULL,
  name VARCHAR(150) NOT NULL,
  title VARCHAR(50) NOT NULL DEFAULT 'HEADSTAFF',
  type ENUM('school', 'college') NOT NULL DEFAULT 'school',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE staff
  ADD COLUMN IF NOT EXISTS image_url VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS title VARCHAR(50) NOT NULL DEFAULT 'HEADSTAFF',
  ADD COLUMN IF NOT EXISTS type ENUM('school', 'college') NOT NULL DEFAULT 'school',
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE staff
  MODIFY COLUMN title VARCHAR(50) NOT NULL DEFAULT 'HEADSTAFF';
